create table USERS (
    ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    GENDER VARCHAR(1) NOT NULL,
    COUNTRY VARCHAR(32) NOT NULL,
    CITY VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL
);