create table FAVORITES (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER, FOREIGN KEY(USER_ID) REFERENCES USERS(id),
    SONG VARCHAR(100) NOT NULL,
    ARTIST VARCHAR(100) NOT NULL,
    IMG VARCHAR(500) NOT NULL,
    URL VARCHAR(500) NOT NULL,
    TAGS VARCHAR(500)
);